[package]
name = "state-tracker-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
azure_core = "0.11.0"
azure_data_cosmos = "0.11.0"
coi = "0.10.1"
coi-actix-web = "0.7.1"
serde = { version = "1.0.160", features = ["derive"] }
serde_derive = "1.0.160"
serde_json = "1.0.96"
toml = "0.7.3"
