version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    #command: ["/cmd_wrapper.sh"]
    volumes:
      - mssql_data:/var/lib/mssqlql/data
      #- ./cmd_wrapper.sh:/cmd_wrapper.sh
      #- ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Statetracker123

volumes:
  mssql_data: